module.exports = [
"Algunos libros son probados, otros devorados, poquísimos masticados y digeridos, Sir Francis Bacon.",
"Allí donde se queman los libros, se acaba por quemar a los hombres, Heinrich Heine.",
"Amar la lectura es trocar horas de hastío por horas de inefable y deliciosa compañía, John Fitzgerald Kennedy.",
"Ante ciertos libros, uno se pregunta: ¿quién los leerá? Y ante ciertas personas uno se pregunta: ¿qué leerán? Y al fin, libros y personas se encuentran, André Gide.",
"Aprender a leer es lo más importante que me ha pasado en la vida, Mario Vargas Llosa.",
"Carecer de libros propios es el colmo de la miseria, Benjamin Franklin.",
"Cuando oigo que un hombre tiene el hábito de la lectura, estoy predispuesto a pensar bien de él, Nicolás de Avellaneda.",
"Cuando rezamos hablamos con Dios, pero cuando leemos es Dios quien habla con nosotros, San Agustín.",
"Cuanto menos se lee, más daño hace lo que se lee, Miguel de Unamuno.",
"De los diversos instrumentos inventados por el hombre, el más asombroso es el libro; todos los demás son extensiones de su cuerpo… Sólo el libro es una extensión de la imaginación y la memoria, Jorge Luis Borges.",
"Detesto la vulgaridad del realismo en la literatura, Al que es capaz de llamarle pala a una pala, deberían obligarle a usar una. Es lo único para lo que sirve, Oscar Wilde.",
"El estudio ha sido para mí el principal remedio contra las preocupaciones de la vida; no habiendo tenido nunca un disgusto que no me haya pasado después de una hora de lectura, Montesquieu.",
"El libro es fuerza, es valor, es fuerza, es alimento; antorcha del pensamiento y manantial del amor, Rubén Darío.",
"El que lee mucho y anda mucho, ve mucho y sabe mucho, Miguel de Cervantes.",
"El regalo de un libro, además de obsequio, es un delicado elogio, Anónimo.",
"El verbo leer, como el verbo amar y el verbo soñar, no soporta el modo imperativo, Daniel Pennac.",
"En muchas ocasiones la lectura de un libro ha hecho la fortuna de un hombre, decidiendo el curso de su vida, Ralph Waldo Emerson.",
"Erotismo y poesía: el primero es una metáfora de la sexualidad, la segunda una erotización del lenguaje, Octavio Paz.",
"Es un buen libro aquel que se abre con expectación y se cierra con provecho, Amos Bronson Alcott.",
"Hacer versos malos depara más felicidad que leer los versos más bellos, Hermann Hesse.",
"He buscado el sosiego en todas partes, y sólo lo he encontrado sentado en un rincón apartado, con un libro en las manos, Thomas De Kempis.",
"La Biblioteca es una esfera cuyo centro cabal es cualquier hexágono, cuya circunferencia es inaccesible, Jorge Luis Borges.",
"La escritura es la pintura de la voz, Voltaire.",
"La lectura de un buen libro es un diálogo incesante en que el libro habla y el alma contesta, André Maurois.",
"La lectura es a la mente lo que el ejercicio al cuerpo, Joseph Addison.",
"La lectura es para mí algo así como la barandilla en los balcones, Nuria Espert .",
"La lectura no da al hombre sabiduría; le da conocimientos, William Somerset Maugham.",
"La lectura nos regala mucha compañía, libertad para ser de otra manera y ser más, Pedro Laín Entralgo.",
"La literatura es el arte de la palabra, Manuel Gayol Fernández.",
"La literatura es siempre una expedición a la verdad, Franz Kafka.",
"La más noble función de un escritor es dar testimonio, como acta notarial y como fiel cronista, del tiempo que le ha tocado vivir, Camilo José Cela.",
"La pluma es la lengua del alma, Miguel de Cervantes.",
"La poesía no quiere adeptos, quiere amantes, Federico García Lorca.",
"Lee y conducirás, no leas y serás conducido, Santa Teresa de Jesús.",
"Leer un libro enseña más que hablar con su autor, porque el autor, en el libro, sólo ha puesto sus mejores pensamientos, René Descartes.",
"Libros, caminos y días dan al hombre sabiduría, Proverbio árabe.",
"Los libros no se han hecho para servir de adorno: sin embargo, nada hay que embellezca tanto como ellos en el interior del hogar, Harriet Beecher Stowe .",
"Los libros que el mundo llama inmorales son los que muestran su propia vergüenza, Oscar Wilde.",
"Los libros son amigos que nunca decepcionan, Thomas Carlyle.",
"Los libros son el mejor viático que he encontrado para este humano viaje, Michel Eyquem de Montaigne.",
"Los libros son las abejas que llevan el polen de una inteligencia a otra, James Russell Lowell.",
"Los libros son, entre mis consejeros, los que más me agradan, porque ni el temor ni la esperanza les impiden decirme lo que debo hacer, Alfonso V el Magnánimo.",
"Ningún escritor joven desea tanto la crítica constructiva como la alabanza, William Hill.",
"Nunca releo mis libros, porque me da miedo, Gabriel García Márquez.",
"Ser escritor es robarle vida a la muerte, Alfredo Conde.",
"Si cerca de la biblioteca tenéis un jardín ya no os faltará de nada,  Cicerón.",
"Un hogar sin libros es como un cuerpo sin alma, Cicerón.",
"Un libro abierto es un cerebro que habla; cerrado un amigo que espera; olvidado, un alma que perdona; destruido, un corazón que llora, Proverbio hindú.",
"Un libro es un regalo estupendo, porque muchas personas sólo leen para no tener que pensar, André Maurois.",
"Uno no es lo que es por lo que escribe, sino por lo que ha leído, Jorge Luis Borges.",
"A veces lees un libro tan especial que quieres llevarlo contigo durante meses, incluso después de haberlo terminado, sólo para estar cerca de él, Marcus Zusak.",
"Adquirir el hábito de la lectura y rodearnos de buenos libros es construirnos un refugio moral que nos protege de casi todas las miserias de la vida, W., Somerset Maugham.",
"Aprender a leer es encender un fuego, cada sílaba que se deletrea es una chispa, Victor Hugo.",
"Cada poema es único. En cada obra late, con mayor o menor grado, toda la poesía. Cada lector busca algo en el poema. Y no es insólito que lo encuentre: Ya lo llevaba dentro, Octavio Paz.",
"Con nuestros amigos los libros, si pasamos una velada en su compañía, es solo y porque realmente nos apetece, Marcel Proust.",
"Creo que la literatura tiene algo más que hacer que divertir: debe tener razón, Max Aub.",
"Creo que parte de mi amor a la vida se lo debo a mi amor a los libros, Adolfo Bioy Casares.",
"Creo que vale la pena leer porque los libros ocultan países maravillosos que ignoramos, contienen experiencias que no hemos vivido jamás. Uno es indudablemente más rico después de la lectura, Adolfo Bioy Casares.",
"Cuando aprendas a leer serás libre para siempre, Frederick Douglass.",
"Cuando leemos, creamos nuestras propias imágenes y asociaciones. El libro vive dentro de nosotros, se reinventa en nosotros a medida que lo vamos leyendo, Jostein Gaarder.",
"Cuanto más se lee, menos se imita, Jules Renard.",
"El arte de leer es, en gran parte, el arte de volver a encontrar la vida en los libros, y de comprenderla mejor gracias a ellos, André Maurois.",
"El autor sólo escribe la mitad del libro. De la otra mitad debe ocuparse el lector, Joseph Conrad.",
"El escritor escribe su libro para explicarse a sí mismo lo que no se puede explicar, Gabriel García Márquez.",
"El gran inconveniente de los nuevos libros es que nos privan de leer los antiguos, Joseph Joubert.",
"El gusto por la lectura se adquiere casi siempre en la niñez, y me sorprende que parezca tan difícil inculcarlo, Esther Tusquets.",
"El mundo está lleno de libros preciosos que nadie lee, Umberto Eco.",
"El propósito de la lectura no es conseguir que se vendan más libros, sino que los lectores disfruten más de la vida, Holbrook Jackson.",
"El tiempo para leer, al igual que el tiempo para amar, dilata el tiempo de vivir, Daniel Pennac.",
"En algún lugar de un libro hay una frase esperándonos para darle un sentido a la existencia, Miguel de Cervantes.",
"Escribir es la manera más profunda de leer la vida, Francisco Umbral.",
"Estamos habitados por libros y por amigos, Daniel Pennac.",
"Hablar de lectura obligatoria es como hablar de felicidad obligatoria, Jorge Luis Borges.",
"Estar a solas con un buen libro es ser capaz de comprenderte más a ti mismo, Harold Bloom.",
"Hace muy poco tiempo, comprendí que la literatura no es algo menor, sino el arte supremo, César Aira.",
"Hay más tesoros en los libros que en todo el botín de los piratas de la Isla del Tesoro, Walt Disney.",
"Hay peores cosas que quemar libros, una de ellas es no leerlos, Ray Bradbury.",
"Hay quienes no pueden imaginar un mundo sin pájaros; hay quienes no pueden imaginar un mundo sin agua; en lo que a mi se refiere, soy incapaz de imaginar un mundo sin libros, Jorge Luis Borges.",
"Hay solo dos cosas con las que uno se puede acostar: una persona y un libro, Ray Bradbury.",
"Junto con los libros debiera venderse el tiempo suficiente para leerlos, Arthur Schopenhauer.",
"La educación ha logrado que las personas aprendan a leer, pero es incapaz de señalar lo que vale la pena leer, George Trevelyan.",
"La ilusión es hacer creer que la literatura es muy similar a la vida y es exactamente lo contrario. La vida es amorfa, la literatura es formal, Françoise Sagan.",
"La lectura adelanta el tiempo de la vida y, paradójicamente, aleja el de la muerte. Leer es buscar otras realidades para comprender mejor esta realidad, Fabricio Caivano.",
"La lectura es el único medio a través del cual nos deslizamos, involuntariamente, a menudo sin poder hacer nada, a la piel de otro, a la voz de otro, al alma de otro, Joyce Carol Oates.",
"La lectura es el viaje de los que no pueden tomar el tren, Francis de Croisset.",
"La lectura es placer, conocimiento, emoción, enajenación, Fernando Trueba.",
"La lectura es un acto de creación permanente, Daniel Pennac.",
"La lectura obligada es nefasta. Lean por placer, tengan una profunda sospecha, Álvaro Mutis.",
"La lectura, como el amor, es la piedra ideal para afinar el alma, Paul Desalmand.",
"La literatura es esencialmente soledad. Se escribe en soledad, se lee en soledad y, pese a todo, el acto de la lectura permite una comunicación profunda entre los seres humanos, Paul Auster.",
"La literatura es la sinceridad misma, la única expresión auténtica de la vida, Joseph Roth.",
"La literatura es una extraña máquina que traga, que absorbe todos los placeres, todos los acontecimientos de la vida. Los escritores son vampiros, Bernard Henri Levy.",
"La literatura está llena de cosas inútiles absolutamente necesarias, Rosa Montero.",
"La literatura no es otra cosa que un sueño dirigido, Jorge Luis Borges.",
"La literatura nos permite comprender la vida, nos habla de lo que puede ser pero también de lo que pudo haber sido… No hay nada más subversivo que la literatura, Enrique Vila-Matas.",
"La mejor característica de un libro es que provoque reacciones en el lector y le empuje a actuar, Thomas Carlyle.",
"La mujer que lee, almacena su belleza para la vejez, Frida Kahlo.",
"La radio marca los minutos de la vida; el diario, las horas; el libro, los días, Jacques de Lacretelle.",
"Las personas libres jamás podrán concebir lo que los libros significan para quienes vivimos encerrados, Ana Frank.",
"Leemos para saber que no estamos solos, William Nicholson.",
"Leemos, pero también somos leídos por otro. Interferencias entre ambas lecturas. Obligar a alguien a que sea a sí mismo como le leen los demás (esclavitud). Obligar a los demás a que nos lean como nos leemos a nosotros mismos (conquista), Simone Weil.",
"Leer es encontrar algo que va a existir, Italo Calvino.",
"Leer lo es todo. La lectura me hace sentir que he logrado algo, he aprendido algo, que soy mejor persona, Nora Ephron.",
"Leer no es matar el tiempo, sino fecundarlo, Herminia Brumana.",
"Lo único que lamento es que nunca tendré tiempo para leer todos los libros que quiero leer, Françoise Sagan.",
"Los buenos libros son siempre campos magnéticos de cuya atracción no se puede huir, Italo Calvino.",
"Los libros han ganado más batallas que las armas, Lupercio Leonardo de Argensola.",
"Los libros solo se escriben para, por encima del propio aliento, unir a los seres humanos, y así defendernos frente al inexorable reverso de la existencia : la fugacidad y el olvido, Stefan Zweig.",
"Los libros sólo tienen valor cuando conducen a la vida y le son útiles, Hermann Hesse.",
"Los libros son como espejos: mirándonos en ellos descubrimos quiénes somos, José Luis de Villalonga.",
"Los libros son compañeros, maestros, magos y banqueros de los tesoros de la mente, Bárbara Wertheim Tuckman.",
"Los libros tienen los mismos enemigos que los hombres: el fuego, la humedad, los animales y su propio contenido, Paul Valéry.",
"Los libros van siendo el único lugar de la casa donde todavía se puede estar tranquilo, Julio Cortázar.",
"Los que escriben con claridad tienen lectores; los que escriben oscuramente tienen comentaristas, Albert Camus.",
"Los verdaderos escritores son aquellos que quieren escribir, necesitan escribir, tienen que escribir, Robert Penn Warren.",
"Me resisto a considerar el afán de leer una simple afición entre otras: es una pasión, aún más, una forma de vida, Fernando Savater.",
"Mis libros están siempre a mi disposición, nunca están ocupados, Marco Tulio Cicerón.",
"No es cierto que tengamos sólo una vida: si leemos podemos vivir tantas y de tantos tipos como queramos, Samuel I. Hayakawa.",
"No existen más que dos reglas para escribir: tener algo que decir y decirlo, Oscar Wilde.",
"No hay ninguna lectura peligrosa. El mal no entra nunca por la inteligencia cuando el corazón está sano, Jacinto Benavente.",
"No importa lo ocupado que creas que estás, debes encontrar un hueco para la lectura. De lo contrario habrás escogido sumirte en la más absoluta ignorancia, Confucio.",
"No lean, como hacen los niños, para divertirse, o como hacen los ambicioso, con el propósito de la instrucción. No, lee para vivir, Gustave Flaubert.",
"Nunca se termina de aprender a leer. Tal vez como nunca se termine de aprender a vivir, Jorge Luis Borges.",
"Ordenar bibliotecas es ejercer de un modo silencioso el arte de la crítica, Jorge Luis Borges.",
"Por grandes y profundos que sean los conocimientos de un hombre, el día menos pensado encuentra en el libro que menos valga a sus ojos, alguna frase que le enseña algo que ignora, Mariano José de Larra.",
"Porque un libro que no abres es condenarlo a una especie de purgatorio esperando que alguien le de vida, Alberto Manguel.",
"Quien escribe lo que le gusta a los demás puede ser un buen escritor pero nunca será un artista, Juan Carlos Onetti.",
"Sabes que has leído un buen libro cuando al cerrar la tapa después de haber leído la última página te sientes como si hubieras perdido a un amigo, Paul Sweeney.",
"Si no podéis disfrutar leyendo un libro repetidas veces, de nada sirve leerlo ni una sola vez, Oscar Wilde.",
"Si piensas llegar a alguna parte en la vida, tienes que leer muchos libros, Roald Dahl.",
"Si un libro está bien escrito, siempre me parece que es demasiado corto, Jane Austen.",
"Siempre imaginé que el Paraíso sería algún tipo de biblioteca, Jorge Luis Borges.",
"Soy un lector que escribe libros; si fuera sólo escritor estaría muerto, Arturo Perez-Reverte.",
"Soy una persona anticuada que cree que leer libros es el pasatiempo más hermoso que la humanidad ha creado, Wislawa Szymborska.",
"Tienes que amar la lectura para poder ser un buen escritor, porque escribir no empieza contigo, Carlos Fuentes.",
"Todos los libros pueden dividirse en dos clases: libros del momento y libros de todo momento, John Ruskin.",
"Un buen libro no es aquel que piensa por ti, sino aquel que te hace pensar, James McCosh.",
"Un buen libro no sólo se escribe para multiplicar y transmitir la voz, sino también para perpetuarla, John Ruskin.",
"Un escritor es algo extraño. Es una contradicción y también un sinsentido. Escribir también es no hablar. Es callarse. Es aullar sin ruido, Marguerite Duras.",
"Un lector vive mil vidas antes de morir. Aquel que nunca lee vive solo una, George R. R. Martin.",
"Un libro de cabecera no se escoge, se enamora uno de él, José Luis de Villalonga.",
"Un libro debe ser el hacha que rompa el mar helado que hay dentro de nosotros, Franz Kafka.",
"Un libro es la única cosa inmortal, Rufus Choate.",
"Un libro es una cosa entre las cosas, un volumen perdido entre los volúmenes que pueblan el indiferente universo; hasta que da con su lector, con el hombre destinado a sus símbolos, Jorge Luis Borges.",
"Un libro es una prueba de que los seres humanos son capaces de hacer magia, Carl Sagan.",
"Un libro, un verdadero libro, no es alguien que nos hable, es alguien que nos oye, que sabe oírnos, Christian Bobin.",
"Uno escribe pensando en el lector que lleva dentro. Escribes o intentas escribir el libro que te gustaría leer, Rosa Montero.",
"Uno nunca termina de leer, aunque los libros se acaben, Roberto Bolaño.",
"Usted no tiene que quemar libros para destruir una cultura. Sólo tiene que hacer que la gente deje de leerlos, Ray Bradbury.",
"Vivir sin leer es peligroso, porque obliga a conformarse con la vida, Michael Houellebecq."
]